import globals

# Truck 1
globals.truck1.add_package(globals.packageHash.search(13))
globals.truck1.add_package(globals.packageHash.search(14))
globals.truck1.add_package(globals.packageHash.search(15))
globals.truck1.add_package(globals.packageHash.search(16))
globals.truck1.add_package(globals.packageHash.search(19))
globals.truck1.add_package(globals.packageHash.search(20))
globals.truck1.add_package(globals.packageHash.search(34))
globals.truck1.add_package(globals.packageHash.search(2))
globals.truck1.add_package(globals.packageHash.search(4))
globals.truck1.add_package(globals.packageHash.search(5))
globals.truck1.add_package(globals.packageHash.search(7))
globals.truck1.add_package(globals.packageHash.search(8))
globals.truck1.add_package(globals.packageHash.search(10))
globals.truck1.add_package(globals.packageHash.search(11))
globals.truck1.add_package(globals.packageHash.search(12))
globals.truck1.add_package(globals.packageHash.search(17))

# Truck 2
globals.truck2.add_package(globals.packageHash.search(1))
globals.truck2.add_package(globals.packageHash.search(29))
globals.truck2.add_package(globals.packageHash.search(30))
globals.truck2.add_package(globals.packageHash.search(37))
globals.truck2.add_package(globals.packageHash.search(31))
globals.truck2.add_package(globals.packageHash.search(40))
globals.truck2.add_package(globals.packageHash.search(3))
globals.truck2.add_package(globals.packageHash.search(18))
globals.truck2.add_package(globals.packageHash.search(36))
globals.truck2.add_package(globals.packageHash.search(38))
globals.truck2.add_package(globals.packageHash.search(21))
globals.truck2.add_package(globals.packageHash.search(22))
globals.truck2.add_package(globals.packageHash.search(23))
globals.truck2.add_package(globals.packageHash.search(24))
globals.truck2.add_package(globals.packageHash.search(26))
globals.truck2.add_package(globals.packageHash.search(27))

# Truck 3
globals.truck3.add_package(globals.packageHash.search(6))
globals.truck3.add_package(globals.packageHash.search(25))
globals.truck3.add_package(globals.packageHash.search(28))
globals.truck3.add_package(globals.packageHash.search(32))
globals.truck3.add_package(globals.packageHash.search(9))
globals.truck3.add_package(globals.packageHash.search(33))
globals.truck3.add_package(globals.packageHash.search(35))
globals.truck3.add_package(globals.packageHash.search(39))
